config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/eosc-search-service:
      branch: 1628-getting-golden-SQA-badge-v3
      repo: https://github.com/cyfronet-fid/eosc-search-service/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-coral-pig.sh
        container: qc.acc_sloppy-dandelion-booby
  QC.Doc:
    repos:
      github.com/cyfronet-fid/eosc-search-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cinnamon-spoonbill.sh
        container: qc.doc_thirsty-fuchsia-ragdoll
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lemon-spaniel.sh
        container: qc.doc_sickly-xanthic-impala
      github.com/cyfronet-fid/eosc-search-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bistre-gorilla.sh
        container: qc.doc_nerdy-harlequin-opossum
  QC.Lic:
    repos:
      github.com/cyfronet-fid/eosc-search-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-celadon-angelfish.sh
        container: qc.lic_droopy-violet-fly
  QC.Met:
    repos:
      github.com/cyfronet-fid/eosc-search-service cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-bistre-bloodhound.sh
        container: qc.met_paltry-carmine-bordeaux
  QC.Sec:
    repos:
      github.com/cyfronet-fid/eosc-search-service bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cinnabar-giraffe.sh
        container: qc.sec_goopy-buff-markhor
  QC.Sty:
    repos:
      github.com/cyfronet-fid/eosc-search-service flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sepia-quail.sh
        container: qc.sty_ugly-blue-neanderthal
      github.com/cyfronet-fid/eosc-search-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ivory-ant.sh
        container: qc.sty_skanky-zucchini-fousek
      github.com/cyfronet-fid/eosc-search-service jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-lavender-okapi.sh
        container: qc.sty_crabby-cobalt-kudu
  QC.Uni:
    repos:
      github.com/cyfronet-fid/eosc-search-service pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-aqua-cassowary.sh
        container: qc.uni_sleazy-firebrick-jaguar
  QC.Ver:
    repos:
      github.com/cyfronet-fid/eosc-search-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-corn-burmese.sh
        container: qc.ver_messy-bistre-tiger
timeout: 5400
