config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/eosc-search-service:
      branch: 1628-getting-golden-SQA-badge-v3
      repo: https://github.com/cyfronet-fid/eosc-search-service
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cyan-spaniel.sh
        container: qc.acc_hilly-taupe-setter
  QC.Doc:
    repos:
      github.com/cyfronet-fid/eosc-search-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-linen-squirt.sh
        container: qc.doc_paltry-rose-flamingo
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-malachite-dodo.sh
        container: qc.doc_droopy-flax-emu
      github.com/cyfronet-fid/eosc-search-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olivine-newt.sh
        container: qc.doc_messy-plum-neanderthal
  QC.Lic:
    repos:
      github.com/cyfronet-fid/eosc-search-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-purple-guppy.sh
        container: qc.lic_frumpy-peach-wrasse
  QC.Met:
    repos:
      github.com/cyfronet-fid/eosc-search-service cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-corn-mammoth.sh
        container: qc.met_stealthy-taupe-swan
  QC.Sec:
    repos:
      github.com/cyfronet-fid/eosc-search-service bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-dandelion-dormouse.sh
        container: qc.sec_queasy-silver-dhole
  QC.Sty:
    repos:
      github.com/cyfronet-fid/eosc-search-service flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-persimmon-clam.sh
        container: qc.sty_trippy-auburn-bullfrog
      github.com/cyfronet-fid/eosc-search-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cinnamon-penguin.sh
        container: qc.sty_smelly-pear-camel
      github.com/cyfronet-fid/eosc-search-service jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-viridian-tang.sh
        container: qc.sty_surly-emerald-leopard
  QC.Uni:
    repos:
      github.com/cyfronet-fid/eosc-search-service pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cobalt-swan.sh
        container: qc.uni_whiny-linen-dog
  QC.Ver:
    repos:
      github.com/cyfronet-fid/eosc-search-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-periwinkle-orangutan.sh
        container: qc.ver_shaggy-cerise-woodpecker
timeout: 5400
